Fix RawRepresentable's JSON coding
omochi/CodableToTypeScript pull request #108
Opened 2023-08-31 00:49 UTC by sidepelican

RawRepresentableに関して大きめの改修をします。

## 課題

現在のC2TSはすべてのRawRepresentableについてJSON表現を`rawValue`に転写していますが、これは誤りでした。
Swift標準ライブラリをよく見ると、`rawValue`への転写はConditional Conformanceで一部のプリミティブ型にのみ実装されています。またOptionalなどには実装はされていません。

JSONへのコーディング規則を標準と揃えるために、`RawRepresentable`なCodingをすべきかどうかの判定をより厳密に行うよう修正します。
あくまでJSON表現のみの変更であり、Entity表現に関しては変化させません。

## 変更内容

- `rawValueType()` をenum用とstruct用に分割します。これはdeclではなくtypeにextension関数を生やすことで、型パラメータを利用して`RawValue`を解決するために必要でした。
- 転写対象の`RawValue`かどうかをより厳密にします。（これまでは`Bool`と`Double`と`Float`が漏れていました）
- あるRawRepresentableなSwift型のTS型を考えるときに、新規のTS型名を与えずに直接参照先のプリミティブ型を返すパスを追加します。これはジェネリックな型が型パラメータによって`rawValue`への転写が切り替わる際に、TS型の定義が複雑化するのを防ぐためです。

2023-08-31 00:57 UTC, sidepelican commented on Tests/CodableToTypeScriptTests/Generate/GenerateRawRepresentableTests.swift
> +    a: string;
これまで `S_JSON`だったが、直接 `string`に解決されるようになった。このテストケースでは不要な変更だが、`S`がジェネリックな場合に必要になる。

2023-08-31 00:57 UTC, sidepelican commented on Tests/CodableToTypeScriptTests/Generate/GenerateRawRepresentableTests.swift
> +    rawValue?: number;
optionalは転写対象ではない

2023-08-31 00:57 UTC, sidepelican commented on Tests/CodableToTypeScriptTests/Generate/GenerateRawRepresentableTests.swift
> +    a: number;
ここに`S_JSON<number>` と表現すると、`S_JSON`は

```ts
type S_JSON<T> = T extends number ? number : {
  rawValue: T;
};
```

のように定義する必要がでてきてしまう。実際は`T extends number`かどうかの判断は誤りであり、boolやstringも含まれるし、TypeMapなどの影響で`URL`などが`string`に解決された場合も転写が行われてしまい、おかしなことになる。
よって利用側で`number`と解決させるようにしている。

2023-08-31 01:13 UTC, sidepelican commented
しまった、decode/encode用の関数も同様に特殊化しなければいけない・・・

2023-08-31 02:48 UTC, sidepelican commented on Tests/CodableToTypeScriptTests/Generate/GenerateRawRepresentableTests.swift
> +    a: string;
これは`RawValue`がジェネリックかどうかを厳密に検査するようになったことにより、変更がなくなりました

2023-08-31 02:50 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +            return rawValueType
型パラが存在するかどうかは後で必要なため、ここでは元の型を返す

2023-09-04 02:55 UTC, omochi commented
ありがとうございます。

Swift標準のRawRepresentableとC2TSの実装がズレているというのは重要な指摘です。
しかし、このトピックは設計上の重要な論点を含むと思われるため、
いったん仕様と設計についてよく検討してから進めたいです。

変更内容として説明を書いてもらっていますが、
これが実装目線になっているため設計の観点で理解しづらいです。

まずはいったん、C2TSのコード生成器としてのユーザ目線で、
どのような変更を考えているのかを明らかにしたいです。

特に、テストコードへのコード差分が、
既存実装の削除も含んでいる関係でわかりづらいです。

とはいえ、ある程度話の趣旨はわかるので、
以下にこちらで論点を整理します。

# 問題点

通常のSwiftは、 `RawRepresentable & Codable` な型について、
特別な転写(`RawValue` 型と全く同じJSON表現にエンコードする事)の実装を持たない。

転写が起きるのは `RawValue` が一部の `Int` などの場合だけ。
そうでない一般の場合については、通常の struct の Codable自動実装と同じエンコーディングとなる。

## 従来のコード生成

従来は下記のSwiftコードに対して

```swift
struct K: Codable {
    var a: Int
}

struct S: RawRepresentable & Codable {
    var rawValue: K
}
```

下記のコード生成が起きる。

```ts
type S = { rawValue: K };
// これが間違い
type S_JSON = K_JSON;
```

しかし、これは普通に間違っている。

## あるべきコード生成

Swift標準では下記のようになるべきである。

```ts
type S = { rawValue: K };
type S_JSON = { rawValue: K_JSON };
```

## ジェネリックな場合

`RawValue` がジェネリックな場合を考える。
下記のような場合を考える。

```swift
struct S<X: Codable>: RawRepresentale & Codable {
    var rawValue: X
}
```

Swift標準において、 `RawValue == Int` の場合に転写になるように定義されているので、
これは `X` の型によってJSON表現が変化しそうに見えるが、そうはならない。

```swift
import Foundation

struct K: Codable { var a: Int }

struct S<X: Codable>: RawRepresentable & Codable {
    var rawValue: X
}

func test<X: Codable>(_ x: X) throws {
    try printJSON(S<X>(rawValue: x))
}

func printJSON<X: Codable>(_ x: X) throws {
    let e = JSONEncoder()
    let data = try e.encode(x)
    print(String(data: data, encoding: .utf8)!)
}

func staticS() throws {
    print("staticS")

    let v0 = S<Int>(rawValue: 1)
    try printJSON(v0)

    let v1 = S<K>(rawValue: K(a: 1))
    try printJSON(v1)
}

func dynamicS() throws {
    print("dynamicS")
    let vs: [any Codable] = [Int(1), K(a: 1)]
    for v in vs {
        // implicit open: any Codable => <X: Encodable>
        try test(v)
    }
}
```

** 出力 **

```
staticS
{"rawValue":1}
{"rawValue":{"a":1}}
dynamicS
{"rawValue":1}
{"rawValue":{"a":1}}
```

このように、`RawValue` がジェネリックな場合における `JSON` 表現は、
一般の場合の挙動で一貫している。

---

# 提案してくれた手法について

> あるRawRepresentableなSwift型のTS型を考えるときに、新規のTS型名を与えずに直接参照先のプリミティブ型を返すパスを追加します。

従来は、あるSwiftの型 `S` において、
そのTSでの型 `S` と、TSでのJSONの型 `S_JSON` が存在するというのを基本としています。

この `S_JSON` を生成しないようにする、という意味に解釈しました。

この `S_JSON` は設計上の前提になっており、
それを出現させないという変更は、
コーナーケースで様々な問題が発生する事が想定されます。

この手法の提案理由について詳しく説明してほしいです。

---

# 目指したい方向性

この問題にどのような対処をするにせよ、大きく目指したい方向性を伝えます。

ライブラリ製品としてみたC2TSの機能としては、
以下のような機能をユーザに提供したいです。

## デフォルトでは、あるべき挙動をする

Swift標準に基づいた自然な挙動を提供します。
これは従来の挙動は指摘の通りの問題があるので、直したいですね

## 簡単にカスタマイズできる

僕はSwift標準から外れて、 `Int` や `String` と同様に、
全ての `RawRepresentable` が転写コーディングを持つようにするのが好きです。

これは `Int` など特殊な場合と、一般の場合で、挙動に一貫性がある方がわかりやすいからです。

C2TSとしては、このようなSwiftユーザの環境でも、
カスタマイズ設定として対応したコード生成を行えるようにしたいです。
また、そのカスタマイズもAPIとして簡単に利用できるようにしたいです。

そして、現状の問題のある挙動はただ削除することはありません。
従来の挙動を利用していたユーザは、
このカスタマイズ設定を利用するように切り替えることで、
ツールとして同じ挙動を維持できるようにしたいです。

現状の仕組みだと、このカスタマイズを指定するのは、
custom type converter がうまく機能すると思っています。

type converterは、あるSwiftの型をTSでどう扱うかの知識を全て持っているオブジェクトです。

これを以下のように整理する事を考えています。

まず従来の `StructTypeConverter` を維持する。
これは、struct の標準的なCodable生成の挙動を持っています。
これは一般的なRawRepresentableのコーディングと同じです。

次に、 従来の `RawRepresentableTypeConverter` を
`RawValueTransferringTypeConverter` にリネームします。
より実態に即した名前にするためです。
これは、「転写になる場合の `RawRepesentable` 」の挙動を持ちます。

さて、標準の挙動では、
対象の型が `RawRepresentable` かつ、転写になる型の場合は、
`RawValueTransferringTypeConverter` を選択するようにします。
そして、転写にならない型の場合は、 `StructTypeConverter` を選択するようにします。

これで Swift標準と挙動が一致するはずです。

その元で、常に転写する環境の場合はカスタマイズとして、
`RawRepresentable` であれば、 `RawValue` の型によらず、
固定で `RawValueTransferringTypeConverter` を選択するように設定します。

こうすると、従来の挙動が提供できるはずです。

2023-09-05 07:20 UTC, sidepelican commented
> RawValue がジェネリックな場合における JSON 表現は、
一般の場合の挙動で一貫している。

これ気づいてませんでした。。。自分で検証したときは複雑な型を使ったせいで勘違いしてジェネリックに変化するものだと考えていました。貼ってもらったコードを自分でも検証して確認しました。
いまの実装はこのジェネリックに変化する部分を再現してるので複雑になってしまってますね


> 提案してくれた手法について

（RawValueがジェネリックな場合にcodingもジェネリックに変化する前提で）
`S_JSON`を出現させないことは、 https://github.com/omochi/CodableToTypeScript/pull/108#discussion_r1310983929 で述べたように、`S_JSON`を正しく定義することが困難であることから、`S_JSON`の直接利用を抑制して特殊化する対応をとっていました。


しかし、実際は`RawValue`がジェネリックな場合は型パラに関わらず一般の挙動をしていたため、`S_JSON`の定義は容易であり不要なロジックでした


> 目指したい方向性

デフォルト挙動をSwift標準に合わせることは同意です。
簡単にカスタマイズする方法についても方針良いと思ったので、そのように実装してみたいと思います。既存の削除したテストについては、`TypeConverterProvider.CustomProvider`をカスタムして`RawValueTransferringTypeConverter`を使った場合のテストとして転用しようかと思います。

2023-09-05 09:23 UTC, sidepelican reviewed
@omochi 指摘事項にあわせて修正しました。
テストはRawValue転写とカスタムのものが1つのテストクラスに混ざってますが、一旦はdiffの見やすさを優先して混ざったままにしています。

また各種TypeConverterについて、カスタムする際に利用側が通常挙動にフォールバックさせたいなどの場合に標準実装を取り出したいと思うので、特殊なものを除いてpublicにしました

2023-09-05 09:32 UTC, sidepelican commented on Tests/CodableToTypeScriptTests/Generate/GenerateRawRepresentableTests.swift
> +    private let rawValueTransferCodingProvider: TypeConverterProvider.CustomProvider = { (generator, stype) in
カスタムする場合の注入ロジック

2023-09-05 09:32 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +    public func rawValueType(checkRawRepresentableCodingType: Bool = true) -> (any SType)? {
結局本質的なロジックの変化はここだけになった。これまでよりRawValueが指定の型かどうかを厳密に検査する。

2023-09-05 10:26 UTC, omochi requested changes
ありがとうございます。
TypeConverterの差し替えによって従来の挙動を再現する設計がうまく実装できたようで嬉しいです。

インラインで指摘した部分だけロジックがよくわからなかったので回答お願いします。

2023-09-05 10:26 UTC, omochi commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
ここのcontext substitution mapの適用によって `rawValueType` が返るか `nil` になるかは、
どのようなSwiftソース入力の場合と対応しているのか、
よくわからないのでテストケースがほしいです。

2023-09-05 12:11 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
これは`testGenericParamApplyIdentity`が対応してますね。

```swift
struct S<T>: RawRepresentable {
    var rawValue: T
}

struct K {
    var a: S<Int>
}
```

に対してそのまま検査すると`S<Int>`を見た際に`T`がプリミティブかどうか検査しちゃうんですよね。Tはこの時点だとアーキタイプのままなので、置換を適用してあげることで`Int`だと判断できるようにしています。

が、これ現状あってもなくても `testGenericParamApplyIdentity` の実質的な結果は変わらないですね。
`rawValueType(checkRawRepresentableCodingType:)` の粒度でみると`S<Int>`を検出できるようになってはいますが、`S<Int>`に対して`rawValueType(checkRawRepresentableCodingType: true)`を呼んだ場合に値が返ってくるべきか、そうでないかが論点になりそうです

2023-09-05 12:21 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
`Int`はRawRepresentableCodingTypeだけど、一度ジェネリックになってる時点でCodable表現はrawValueのままなので、ここはnilが返ってくるべきかなぁ

2023-09-05 13:35 UTC, omochi commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
なるほど。

まずenumの方の `rawValueType` は意味が明確ですね。

`isRawRepresentableCodingType` メソッドと、
`checkRawRepresentableCodingType` については、
「転写になる型かどうか」を言ってると思うので、
これは `RawValueTransferringConverter` と命名を揃えて、
`isTransferringRawValueType` と、
`requiresTransferringRawValueType` にリネームしてはどうでしょう？

そしてラベルを `requires` にする事で、
「転写になる型でなければnilを返すアクセサ」である事が伝わりやすくなると思います。

この仕様の元で考えれば、
`S<Int>` の場合でも
`rawValueType(requiresTransferringRawValueType:)` は、
`S<T>` は転写しないので、
`requires...` が `true` の場合は `nil` が返って、
`false` の場合は `Int` が返る、で良いと思います。

2023-09-06 01:47 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
命名の意味合いをすこしずらして挙動に合わせるのは良いですね。そのようにしました 9ac4a7d517231662cb174cea50dc3ef01b97d21a

2023-09-06 01:57 UTC, sidepelican commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
ついでにテストも足して、`rawValueType(requiresTransferringRawValueType: false)` のときは解決後の型を返すようにしました（これは現在特に利用用途はないけど、そっちのほうが直感的に思えたので）
例: `S<Int>`の場合`T`ではなく`Int`が返る

2023-09-06 02:05 UTC, omochi commented on Sources/CodableToTypeScript/Extensions/STypeEx.swift
> +        if resolved.isRawRepresentableCodingType() {
> これは現在特に利用用途はないけど、そっちのほうが直感的に思えた

良いと思います。
declではなくtypeに対する問い合わせなので、
`S<Int>` においては `Int` が得られるのは妥当でしょう。

2023-09-06 02:06 UTC, omochi approved these changes
ありがとうございます、まとまったと思います。

2023-09-06 02:06 UTC, merged